CREATE TABLE loanproducts (
	id INT NOT NULL AUTO_INCREMENT,
	longName VARCHAR(255),
	maxInterestRate DOUBLE,
	minInterestRate DOUBLE,
	shortName VARCHAR(255),
	status INT,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE UNIQUE INDEX shortName ON loanproducts (shortName ASC);


CREATE TABLE loans (
	id INT NOT NULL AUTO_INCREMENT,
	amount DECIMAL(10 , 2),
	clientId INT,
	interestRate DECIMAL(10 , 2),
	LOAN_PRODUCT_ID INT NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE INDEX FK625D983185434A3 ON loans (LOAN_PRODUCT_ID ASC);

ALTER TABLE loans ADD CONSTRAINT FK625D983185434A3 FOREIGN KEY (LOAN_PRODUCT_ID)
	REFERENCES loanproducts (id);