CREATE TABLE office_level (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255),
	LEVEL_ABOVE_ID INT,
	LEVEL_BELOW_ID INT,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

ALTER TABLE office_level ADD CONSTRAINT FK425C3C216D54F46F FOREIGN KEY (LEVEL_ABOVE_ID)
	REFERENCES office_level (id);

ALTER TABLE office_level ADD CONSTRAINT FK425C3C216E6FD35B FOREIGN KEY (LEVEL_BELOW_ID)
	REFERENCES office_level (id);

