CREATE TABLE OFFICE_LEVEL (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255),
	LEVEL_ABOVE_ID INT,
	LEVEL_BELOW_ID INT,
	PRIMARY KEY (ID)
) ENGINE=InnoDB;

ALTER TABLE OFFICE_LEVEL ADD CONSTRAINT FK425C3C216D54F46F FOREIGN KEY (LEVEL_ABOVE_ID)
	REFERENCES OFFICE_LEVEL (ID);

ALTER TABLE OFFICE_LEVEL ADD CONSTRAINT FK425C3C216E6FD35B FOREIGN KEY (LEVEL_BELOW_ID)
	REFERENCES OFFICE_LEVEL (ID);

