#!/bin/bash
# current working directory must be the root of mifos-cheetah project
# DEPLOY_BASE is the directory a tomcat installation will be created in
TOMCAT=apache-tomcat-6.0.18
TOMCAT_DEPLOY=$TOMCAT-mifos-cheetah
export CATALINA_HOME=$DEPLOY_BASE/$TOMCAT_DEPLOY

PROJECT_BUILD_DIR=`pwd`
DEPLOY_RESOURCES=$PROJECT_BUILD_DIR/resources/deploy-build
export CLASSPATH=$DEPLOY_RESOURCES
echo "classpath: $CLASSPATH"

$CATALINA_HOME/bin/catalina.sh stop
rm -rf $DEPLOY_BASE
mkdir $DEPLOY_BASE
cd $DEPLOY_BASE
tar zxf $HOME/arc/$TOMCAT.tar.gz
mv $TOMCAT $TOMCAT_DEPLOY
cp $DEPLOY_RESOURCES/server.xml $DEPLOY_BASE/$TOMCAT_DEPLOY/conf
cp $DEPLOY_RESOURCES/jdbc.local.properties $DEPLOY_BASE/$TOMCAT_DEPLOY/lib
LATEST_CHEETAH_WAR=`find $HOME/.m2/repository/org/mifos -iname "cheetah*.war" |sort -r | head -1`
cp $LATEST_CHEETAH_WAR $TOMCAT_DEPLOY/webapps/mifos.war
$CATALINA_HOME/bin/catalina.sh start
